name: ayni_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  infinite_scroll_pagination: ^4.0.0
  shared_preferences: ^2.0.6
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/ayni.png
  uses-material-design: true
